// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANz_NtIwG6Xv-cmE_DjQ8B0TOGAMEjPhs',
    appId: '1:351918482222:web:6838c4deadaf04d03950bf',
    messagingSenderId: '351918482222',
    projectId: 'shoply-e-commerce',
    authDomain: 'shoply-e-commerce.firebaseapp.com',
    storageBucket: 'shoply-e-commerce.firebasestorage.app',
    measurementId: 'G-BZJ4CZN0MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATOE_xJpGFAPI5RrOlOX0mHsTaaLuGuS0',
    appId: '1:351918482222:android:d8238c97bcd0661a3950bf',
    messagingSenderId: '351918482222',
    projectId: 'shoply-e-commerce',
    storageBucket: 'shoply-e-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbfnG0QxNPGxXrl0Fozm54bBj8BnV9C9g',
    appId: '1:351918482222:ios:84a049bb519b176f3950bf',
    messagingSenderId: '351918482222',
    projectId: 'shoply-e-commerce',
    storageBucket: 'shoply-e-commerce.firebasestorage.app',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbfnG0QxNPGxXrl0Fozm54bBj8BnV9C9g',
    appId: '1:351918482222:ios:84a049bb519b176f3950bf',
    messagingSenderId: '351918482222',
    projectId: 'shoply-e-commerce',
    storageBucket: 'shoply-e-commerce.firebasestorage.app',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANz_NtIwG6Xv-cmE_DjQ8B0TOGAMEjPhs',
    appId: '1:351918482222:web:12b7ba565428fd713950bf',
    messagingSenderId: '351918482222',
    projectId: 'shoply-e-commerce',
    authDomain: 'shoply-e-commerce.firebaseapp.com',
    storageBucket: 'shoply-e-commerce.firebasestorage.app',
    measurementId: 'G-1XFH0Z0MJD',
  );
}
